name: Test manager

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Call Test manager
      id: test-manager
      uses: fjogeleit/http-request-action@master
      with:
        url: 'http://${{ secrets.TEST_MANAGER_HOST }}/runs/5fbf3f769289b6b8388ff310'
        method: 'GET'
#        url: 'http://${{ secrets.TEST_MANAGER_HOST }}/runs/'
#              method: 'POST'
#        bearerToken: ${{ secrets.TEST_MANAGER_TOKEN }}
#        data: '{"template_id": "${{ secrets.TEST_MANAGER_HOST }}"}'
    - name: Check Run Status
      run: |
        export run_id=`echo '${{ steps.test-manager.outputs.response }}' | jq '.data.id'`
        python  toolbuilder/runtest/check_test_status.py $run_id
